name: myenv
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10  # Assuming a reasonable Python version; adjust if needed
  - pip
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scikit-learn=1.4.1
  - scipy=1.12.0
  - torch=2.2.1
  - torchvision=2.2.1
  - cudatoolkit=12.1  # Matches nvidia-cuda-* versions
  - transformers=4.45.2
  - huggingface_hub=0.26.1
  - datasets=2.18.0
  - tensorboard=2.17.1
  - tensorflow=2.17.0
  - keras=3.3.3
  - jupyter=1.0.0
  - ipython=8.22.1
  - jupyterlab=4.1.2
  - notebook=7.1.0
  - ipywidgets=8.1.2
  - tqdm=4.66.2
  - pyyaml=6.0.1
  - requests=2.31.0
  - aiohttp=3.9.3
  - beautifulsoup4=4.12.3
  - h5py=3.11.0
  - pillow=10.2.0
  - pyarrow=15.0.0
  - psutil=5.9.8
  - accelerate=0.27.2
  - bitsandbytes=0.42.0
  - peft=0.13.2
  - safetensors=0.4.2
  - pip:
      - deepspeed==0.14.0  # Not easily available via Conda
      - lion-pytorch==0.1.2  # May need pip
      - opacus==1.5.2  # Privacy-focused, often via pip
      - wandb==0.16.3  # Weights & Biases, better via pip
      - evaluate==0.4.1  # Hugging Face evaluate, often pip
      - tensorboardX==2.6.2.2  # Extra tensorboard tools
      - nvitop==1.3.2  # GPU monitoring, pip-only