wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.45.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1743397997.408304
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.16.3
      6: 4.45.2
      8:
      - 1
      - 5
      13: linux-x86_64
